package UserInterfaces;

import Classes.Cliente;
import Classes.Functions;
import Classes.Produto;
import Classes.Venda;
import Classes.VendaItem;
import DAO.ClienteDAO;
import DAO.VendaDAO;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.KeyStroke;
import javax.swing.InputMap;
import javax.swing.ActionMap;
import javax.swing.JComponent;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class CadastroVenda_pdv extends javax.swing.JFrame {

    public CadastroVenda_pdv() {
        initComponents();
        
        adicionarCalculoAutomatico();
        
        //ATALHO F5
        KeyStroke teclaF5 = KeyStroke.getKeyStroke("F5");
        InputMap im = getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = getRootPane().getActionMap();
        im.put(teclaF5, "acaoF5");
        am.put("acaoF5", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 novoCadastro();
            }
        });
        
             
        // Atalho ESC
        KeyStroke teclaESC = KeyStroke.getKeyStroke("ESCAPE");
        im.put(teclaESC, "acaoESC");
        am.put("acaoESC", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cancelar();
            }
        });
        
         // Atalho F8
        KeyStroke teclaF8 = KeyStroke.getKeyStroke("F8");
        im.put(teclaF8, "acaoF8");
        am.put("acaoF8", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                consultarProduto();
            }
        });
        
        // Atalho F12
        KeyStroke teclaF12 = KeyStroke.getKeyStroke("F12");
        im.put(teclaF12, "acaoF12");
        am.put("acaoF12", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
               consultarCliente();
                
            }
        });
        
        // Atalho F6
        KeyStroke teclaF6 = KeyStroke.getKeyStroke("F6");
        im.put(teclaF6, "acaoF6");
        am.put("acaoF6", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {              
               qtdProduto();                
            }
        });
        
        
         // Atalho DELETE
        KeyStroke teclaDELETE = KeyStroke.getKeyStroke("DELETE");
        im.put(teclaDELETE, "acaoDELETE");
        am.put("acaoDELETE", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {              
               excluirProdutoDaTabela();                
            }
        });
        
        // Atalho ENTER
        KeyStroke teclaENTER = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        im.put(teclaENTER, "acaoENTER");

        am.put("acaoENTER", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                adicionarProdutoNaTabela();
            }
        });
        
         // Atalho F1
        KeyStroke teclaF1 = KeyStroke.getKeyStroke("F1");
        im.put(teclaF1, "acaoF1");
        am.put("acaoF1", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
               consultarCliente();
                
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCodBarras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnFinalizarVenda = new javax.swing.JButton();
        btnItem = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnQtd = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTotalVenda = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ponto de Venda");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("CÓDIGO DE BARRAS");

        txtCodBarras.setEditable(false);
        txtCodBarras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCodBarras.setToolTipText("Insirerir data no formado 01/01/1999");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("CÓDIGO PRODUTO");

        txtCodProduto.setEditable(false);
        txtCodProduto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCodProduto.setToolTipText("Insirerir data no formado 01/01/1999");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("PRODUTO");

        txtProduto.setEditable(false);
        txtProduto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtProduto.setToolTipText("Insirerir data no formado 01/01/1999");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("QTD.");

        txtQtd.setEditable(false);
        txtQtd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtQtd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQtd.setToolTipText("Insirerir data no formado 01/01/1999");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("PREÇO UNIT.");

        txtPreco.setEditable(false);
        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtPreco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPreco.setToolTipText("Insirerir data no formado 01/01/1999");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setToolTipText("Insirerir data no formado 01/01/1999");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("PREÇO TOTAL");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DADOS DO PRODUTO");

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdicionar.setText("ADICIONAR (Enter)");
        btnAdicionar.setEnabled(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        lblMensagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(51, 153, 0));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMensagem.setText("Iniciar nova venda!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6)))
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel10)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lblMensagem)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodProduto)
                    .addComponent(txtCodBarras))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(10, 10, 10)
                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionar)
                .addGap(18, 18, 18)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnNovo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo 16px.png"))); // NOI18N
        btnNovo.setText("Nova Venda (F5)");
        btnNovo.setToolTipText("F5");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnFinalizarVenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFinalizarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo 16px.png"))); // NOI18N
        btnFinalizarVenda.setText("Finalizar Venda (F1)");
        btnFinalizarVenda.setToolTipText("F1");
        btnFinalizarVenda.setEnabled(false);
        btnFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaActionPerformed(evt);
            }
        });

        btnItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Find 16px.png"))); // NOI18N
        btnItem.setText("Consultar Item (F8)");
        btnItem.setToolTipText("F8");
        btnItem.setEnabled(false);
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });

        btnCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fornecedor 16px.png"))); // NOI18N
        btnCliente.setText("Identifica Cliente (F12)");
        btnCliente.setToolTipText("F12");
        btnCliente.setEnabled(false);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnQtd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQtd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Produto 16px.png"))); // NOI18N
        btnQtd.setText("Qtd. Item (F6)");
        btnQtd.setToolTipText("F6");
        btnQtd.setEnabled(false);
        btnQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQtdActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar 16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar Venda (ESC)");
        btnCancelar.setToolTipText("ESC");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluirItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close_sales.png"))); // NOI18N
        btnExcluirItem.setText("Excluir Item (DELETE)");
        btnExcluirItem.setToolTipText("DELETE");
        btnExcluirItem.setEnabled(false);
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinalizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnFinalizarVenda)
                    .addComponent(btnItem)
                    .addComponent(btnCliente)
                    .addComponent(btnQtd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluirItem))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblProdutos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("TOTAL VENDA");

        lblTotalVenda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalVenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalVenda.setText("0.00");
        lblTotalVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NOME:");

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCliente.setToolTipText("Digite o cliente ou pesquise");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CPF:");

        txtCPF.setEditable(false);
        txtCPF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCPF.setToolTipText("Digite o cliente ou pesquise");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DADOS DA VENDA");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("ID");

        txtIdCliente.setEditable(false);
        txtIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdCliente.setToolTipText("Insirerir data no formado 01/01/1999");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCPF)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCliente))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalVenda)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

       adicionarProdutoNaTabela();
       
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
    
        novoCadastro();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaActionPerformed
        salvarVenda();
    }//GEN-LAST:event_btnFinalizarVendaActionPerformed

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
        consultarProduto();   
    }//GEN-LAST:event_btnItemActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        consultarCliente();        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQtdActionPerformed
            qtdProduto();        // TODO add your handling code here:
    }//GEN-LAST:event_btnQtdActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
         excluirProdutoDaTabela();
    }//GEN-LAST:event_btnExcluirItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda_pdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda_pdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda_pdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda_pdv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVenda_pdv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnFinalizarVenda;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnQtd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTotalVenda;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void habilitarCampos() {

        lblMensagem.setText("Venda em andamento...");
        btnAdicionar.setEnabled(true);
        btnFinalizarVenda.setEnabled(true);
        btnItem.setEnabled(true);
        btnCliente.setEnabled(true);
        btnQtd.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnExcluirItem.setEnabled(true);

    }

    private void desabilitarCampos() {

        txtQtd.setEditable(false);
        btnAdicionar.setEnabled(false);
        btnFinalizarVenda.setEnabled(false);
        btnItem.setEnabled(false);
        btnCliente.setEnabled(false);
        btnQtd.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnExcluirItem.setEnabled(false);

    }

    private void limpar() {
        
        
        txtCodBarras.setText("");
        txtCodProduto.setText("");
        txtProduto.setText("");
        txtQtd.setText("");
        txtPreco.setText("");
        txtTotal.setText("");
        lblMensagem.setText("Iniciar nova venda!");
        
       

    }

    private void camposObrigatorios() {

        Functions f = new Functions();
        f.BackgroundCamposObrigatorios(txtQtd);
    }

    private void limparCamposObrigatorios() {

        Functions f = new Functions();
        f.BackgroundCamposBrancos(txtQtd);
    }

    private void novoCadastro() {

        limpar();
        habilitarCampos();

    }

    private void cancelar() {

        limpar();
        desabilitarCampos();
        limparCamposObrigatorios();

    }

    private void consultarCliente() {

        ListClientesDialog dialog = new ListClientesDialog(CadastroVenda_pdv.this);
        Cliente clienteSelecionado = dialog.mostrarDialogo();
        if (clienteSelecionado != null) {
            preencherCampos_Cliente(clienteSelecionado);
        }
    }

    private void preencherCampos_Cliente(Cliente c) {

        txtIdCliente.setText(String.valueOf(c.getId()));
        txtCliente.setText(c.getNome());
        txtCPF.setText(c.getCpf());

    }

    private void consultarProduto() {

        ListProdutosDialog dialog = new ListProdutosDialog(CadastroVenda_pdv.this);
        Produto produtosSelecionado = dialog.mostrarDialogo();
        if (produtosSelecionado != null) {
            preencherCampos_Prod(produtosSelecionado);
        }
    }

    private void preencherCampos_Prod(Produto p) {

        txtCodBarras.setText(p.getCodBarras());
        txtCodProduto.setText(String.valueOf(p.getId()));
        txtProduto.setText(p.getDescricao());
        txtPreco.setText(String.valueOf(p.getPrecoVenda()));
        txtQtd.setText(String.valueOf("1"));

    }

    private void qtdProduto() {

        QtdProdutosDialog dialog = new QtdProdutosDialog(this);
        int qtd = dialog.mostrarDialogo();

        if (qtd > 0) {
            // Aqui você recebe a quantidade digitada e pode usar:
            //System.out.println("Quantidade escolhida: " + qtd);
            txtQtd.setText(String.valueOf(qtd));

            // Exemplo: txtQuantidade.setText(String.valueOf(qtd));
        } else {

            JOptionPane.showMessageDialog(null, "Operação cancelada ou quantidade inválida.");
            // System.out.println("Operação cancelada ou quantidade inválida.");
        }
    }

    // Método para adicionar o listener após a criação dos componentes
    private void adicionarCalculoAutomatico() {
        txtQtd.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                calcularTotal();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                calcularTotal();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                calcularTotal();
            }
        });
    }

    private void calcularTotal() {
        try {
            // Obtendo valores do txtQtd e txtPreco
            double quantidade = Double.parseDouble(txtQtd.getText());
            double preco = Double.parseDouble(txtPreco.getText());

            double total = quantidade * preco;

            // Atualizando o txtTotal com duas casas decimais
            txtTotal.setText(String.format("%.2f", total));
        } catch (NumberFormatException e) {
            // Se o usuário apagar o campo ou digitar algo inválido
            txtTotal.setText("0.00");
        }
    }


    private void limparTabelaProdutos() {
    DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
    modelo.setRowCount(0); // Remove todas as linhas
}
    private ArrayList<VendaItem> listaItensVenda = new ArrayList<>();
    
    private void adicionarProdutoNaTabela() {
        if (txtCodProduto.getText().trim().isEmpty()
            || txtProduto.getText().trim().isEmpty()
            || txtTotal.getText().trim().isEmpty()
            || txtPreco.getText().trim().isEmpty()
            || txtQtd.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos.");
        return;
    }

    // Cria objeto VendaItem
    VendaItem item = new VendaItem();
    item.setProdutoId(Integer.parseInt(txtCodProduto.getText()));
    item.setDescricao(txtProduto.getText());
    item.setQuantidade(Integer.parseInt(txtQtd.getText()));
    item.setPrecoUnitario(Double.parseDouble(txtPreco.getText()));
    item.setTotalItem(item.getQuantidade() * item.getPrecoUnitario());

    // Adiciona no ArrayList correto
    listaItensVenda.add(item);

    montarTabela();

    limpar();

    }
    
double somaTotal = 0.0;

    private TableModel montarTabela() {

        String[] colunas = {"#", "Produto", "Descrição", "Qtd", "Preco Unt.", "Total",};

        //Criando a tabela na mão!
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Impede edição em todas as células
            }
        };

       // double somaTotal = 0.0;  // acumulador do total
        //For para montar as linhas na tabela
       for (int i = 0; i < listaItensVenda.size(); i++) {
        VendaItem item = listaItensVenda.get(i);

        Object[] linha = {  
            i + 1,
            item.getProdutoId(),
            item.getDescricao(),
            item.getQuantidade(),
            String.format("%.2f", item.getPrecoUnitario()),
            String.format("%.2f", item.getTotalItem())
        };

            tabela.addRow(linha);//Não esquecer de adicionar a linha!
            somaTotal += item.getTotalItem();

        }
        tblProdutos.setModel(tabela);
        lblTotalVenda.setText(String.format("%.2f", somaTotal));
        
        tblProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);  // Indice
        tblProdutos.getColumnModel().getColumn(1).setPreferredWidth(50);  // Cod Prod
        tblProdutos.getColumnModel().getColumn(2).setPreferredWidth(200); // Nome
        tblProdutos.getColumnModel().getColumn(3).setPreferredWidth(50); // qtd
        tblProdutos.getColumnModel().getColumn(4).setPreferredWidth(100); // Prec Unt
        tblProdutos.getColumnModel().getColumn(5).setPreferredWidth(100); // Total

        // Configurando o cabeçalho
        JTableHeader header = tblProdutos.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 12));

        // Alinhando o cabeçalho à esquerda
        DefaultTableCellRenderer leftRenderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);

        

        return tabela;

    }

private void excluirProdutoDaTabela() {
    int linhaSelecionada = tblProdutos.getSelectedRow();

    if (linhaSelecionada >= 0) {
        // Confirmação opcional
        int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o item selecionado?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Remove da lista
            listaItensVenda.remove(linhaSelecionada);

            // Atualiza a tabela
            montarTabela();

            JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione um item para excluir.");
    }
}

   private void salvarVenda() {
    Venda v = new Venda();
    v.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
    v.setTotal(somaTotal);
    v.setItens(listaItensVenda); // Adiciona os itens à venda

    if (VendaDAO.salvarVenda(v)) {
        JOptionPane.showMessageDialog(this, "Venda salva com sucesso!");
        limpar();
        txtIdCliente.setText("");
        txtCliente.setText("");
        txtCPF.setText("");
        lblTotalVenda.setText("");
        limparTabelaProdutos();
        limparCamposObrigatorios();
        desabilitarCampos();
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao salvar venda!");
    }
}
        
    
   
    
}

