/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterfaces;

import Classes.Functions;
import Classes.Produto;
import DAO.ProdutoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Wilian
 */
public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtUndMedida = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCusto = new javax.swing.JTextField();
        txtPrecoVenda = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSaldoAtual = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbAtivo = new javax.swing.JRadioButton();
        rbInativo = new javax.swing.JRadioButton();
        cboxControlaSaldo = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtCodBarras = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Descrição:");
        jLabel2.setToolTipText("Descrição do produto");

        txtDescricao.setEditable(false);
        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescricao.setToolTipText("Insirerir descrição do produto");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Categoria:");
        jLabel11.setToolTipText("Inserir CPF no formato 999.999999-99");

        txtCategoria.setEditable(false);
        txtCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategoria.setToolTipText("Categoria do produto");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Und. Med.");
        jLabel12.setToolTipText("Inserir CPF no formato 999.999999-99");

        txtUndMedida.setEditable(false);
        txtUndMedida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUndMedida.setToolTipText("Unidade de medida do produto");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Custo:");
        jLabel13.setToolTipText("Inserir CPF no formato 999.999999-99");

        txtCusto.setEditable(false);
        txtCusto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCusto.setToolTipText("Custo unitario do produto");

        txtPrecoVenda.setEditable(false);
        txtPrecoVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecoVenda.setToolTipText("Preço de venda do Produto");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Preço Venda:");
        jLabel14.setToolTipText("Inserir CPF no formato 999.999999-99");

        txtSaldoAtual.setEditable(false);
        txtSaldoAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSaldoAtual.setToolTipText("Saldo atual em estoque do produto");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Est. Atual:");
        jLabel10.setToolTipText("Insira estado abreviado Ex: \"SP\"");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setToolTipText("Inserir o telefone");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID:");

        rbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbAtivo.setSelected(true);
        rbAtivo.setText("Ativo");
        rbAtivo.setEnabled(false);

        rbInativo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbInativo.setText("Inativo");
        rbInativo.setEnabled(false);

        cboxControlaSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxControlaSaldo.setText("Controla Estoque");
        cboxControlaSaldo.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cód. Barras:");

        txtCodBarras.setEditable(false);
        txtCodBarras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodBarras.setToolTipText("Inserir o telefone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUndMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbInativo))
                            .addComponent(cboxControlaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtUndMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbAtivo)
                        .addComponent(rbInativo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboxControlaSaldo))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnNovo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo 16px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Novo registro");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Find 16px.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Pesquisar cadastro");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save 16px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar cadastro");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Editar 16px.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Editar cadastro");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar 16px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete 16px.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excuir cadastro");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        novoCadastro();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        cancelar();
        ListProdutos telaPesquisa = new ListProdutos(this); // <-- aqui está o segredo Essa nova janela (ListClientes) pertence ao CadastroCliente atual.”
        telaPesquisa.setVisible(true);

        // new ListClientes().setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarCadastro();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editarCadastro();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        excluirCadastro();

    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cboxControlaSaldo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbAtivo;
    private javax.swing.JRadioButton rbInativo;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtCusto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtSaldoAtual;
    private javax.swing.JTextField txtUndMedida;
    // End of variables declaration//GEN-END:variables
 private boolean emptyFields() {

        boolean empty = true;

        if (txtDescricao.getText().trim().isEmpty() || txtPrecoVenda.getText().trim().isEmpty() || txtCusto.getText().trim().isEmpty() || txtSaldoAtual.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ATENÇÃO! Os campos Descrição, custo, preço venda e estoque atual são obrigatórios.");

        } else {
            empty = false;
        }
        return empty;

    }


    private void novoCadastro() {

        camposObrigatorios();
        habilitarCampos();
        
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        limpar();

    }

    private void habilitarCampos() {
        txtCodBarras.setEditable(true);
        txtDescricao.setEditable(true);
        txtCodBarras.requestFocus();
        txtCategoria.setEditable(true);
        txtUndMedida.setEditable(true);
        txtCusto.setEditable(true);
        txtPrecoVenda.setEditable(true);
        txtSaldoAtual.setEditable(true);
        rbAtivo.setEnabled(true);
        rbInativo.setEnabled(true);
        cboxControlaSaldo.setEnabled(true);

        

    }

    private void desabilitarCampos() {
        txtDescricao.setEditable(false);
        txtCodBarras.setEditable(false);
        txtCategoria.setEditable(false);
        txtUndMedida.setEditable(false);
        txtCusto.setEditable(false);
        txtPrecoVenda.setEditable(false);
        txtSaldoAtual.setEditable(false);
        rbAtivo.setEnabled(false);
        rbInativo.setEnabled(false);
        cboxControlaSaldo.setEnabled(false);
        
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnNovo.setEnabled(true);

    }

    private void limpar() {
        txtID.setText("");
        txtCodBarras.setText("");
        txtDescricao.setText("");
        txtCategoria.setText("");
        txtUndMedida.setText("");
        txtCusto.setText("");
        txtPrecoVenda.setText("");
        txtSaldoAtual.setText("");
  
    }

    private void camposObrigatorios() {

        Functions f = new Functions();
        f.BackgroundCamposObrigatorios(txtDescricao);
        f.BackgroundCamposObrigatorios(txtPrecoVenda);
        f.BackgroundCamposObrigatorios(txtCusto);
        f.BackgroundCamposObrigatorios(txtSaldoAtual);
       
    }

    private void limparCamposObrigatorios() {

        Functions f = new Functions();
        f.BackgroundCamposBrancos(txtDescricao);
        f.BackgroundCamposBrancos(txtPrecoVenda);
        f.BackgroundCamposBrancos(txtCusto);
        f.BackgroundCamposBrancos(txtSaldoAtual);
    }

    private void cancelar() {

        limpar();
        desabilitarCampos();
        limparCamposObrigatorios();
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
    }

    private void editarCadastro() {

        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um item para Editar!");
        } else {

            camposObrigatorios();
            habilitarCampos();
            btnExcluir.setEnabled(false);
            btnSalvar.setEnabled(true);
            btnNovo.setEnabled(false);
            btnPesquisar.setEnabled(false);
        }

    }

    private void salvarCadastro() {
        if (!emptyFields()) {

            Produto p = new Produto();

            if (txtID.getText().equals("")) {
                //codigo NOVO CLIENTE para enviar dados para classe consulta
                p.setCodBarras(txtCodBarras.getText());
                p.setDescricao(txtDescricao.getText());
                p.setCategoria(txtCategoria.getText());
                p.setUndMedida(txtUndMedida.getText());
                p.setCusto(Double.parseDouble(txtCusto.getText()));
                p.setPrecoVenda(Double.parseDouble(txtPrecoVenda.getText()));
                p.setSaldo(Integer.parseInt(txtSaldoAtual.getText()));
                
                // CHECK BOX
                if(cboxControlaSaldo.isSelected()){
                p.setControlaSaldo(true);
                } else p.setControlaSaldo(false);
                
                //TRATAR RADIO BUTTON
                if(rbAtivo.isSelected()){
                p.setStatus("Ativo");
                }else if (rbInativo.isSelected()){
                p.setStatus("Inativo");}

                // MUITO IMPORTANTE CHAMAR ESSE METODO PARA ADCIONAR DADOS A LISTA E DEPOIS CARREGAR NO TABLE
                if (ProdutoDAO.cadastrar(p)) {
                    JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!"); //cadastrato com sucesso
                    limpar();
                    limparCamposObrigatorios();
                    desabilitarCampos();

                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto!");
                }//erro ao cadastrar    

            } else {

                //codigo EDITAR CLIENTE para enviar dados para classe consulta
                int id = Integer.parseInt(txtID.getText());
                Produto pes = new Produto();
                //codigo NOVO CLIENTE para enviar dados para classe consulta
                pes.setCodBarras(txtCodBarras.getText());
                pes.setDescricao(txtDescricao.getText());
                pes.setCategoria(txtCategoria.getText());
                pes.setUndMedida(txtUndMedida.getText());
                pes.setCusto(Double.parseDouble(txtCusto.getText()));
                pes.setPrecoVenda(Double.parseDouble(txtPrecoVenda.getText()));
                pes.setSaldo(Integer.parseInt(txtSaldoAtual.getText()));

                // CHECK BOX
                if (cboxControlaSaldo.isSelected()) {
                    pes.setControlaSaldo(true);
                } else {
                    p.setControlaSaldo(false);
                }

                //TRATAR RADIO BUTTON
                if (rbAtivo.isSelected()) {
                    pes.setStatus("Ativo");
                } else if (rbInativo.isSelected()) {
                    pes.setStatus("Inativo");
                }

                // MUITO IMPORTANTE CHAMAR ESSE METODO PARA ADCIONAR DADOS A LISTA E DEPOIS CARREGAR NO TABLE
                if (ProdutoDAO.atualizar(id, pes)) {
                    JOptionPane.showMessageDialog(this, "Produto editado com sucesso!");
                    limpar();
                    limparCamposObrigatorios();
                    desabilitarCampos();

                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao editar  produto!");
                }//erro ao cadastrar 
            }

        }

        
    }

   
    
    public void preencherCampos(Produto p) {
        txtID.setText(String.valueOf(p.getId()));
        txtCodBarras.setText(p.getCodBarras());         
        txtDescricao.setText(p.getDescricao());
        txtCategoria.setText(p.getCategoria());
        txtUndMedida.setText(p.getUndMedida());
        txtCusto.setText(String.valueOf(p.getCusto()));
        txtPrecoVenda.setText(String.valueOf(p.getPrecoVenda()));
        txtSaldoAtual.setText(String.valueOf(p.getSaldo()));
        
        
        //TRATAR RADIAL BUTTON E CHECK BOX
        if(p.isControlaSaldo()){ 
        cboxControlaSaldo.setSelected(true);
        } else cboxControlaSaldo.setSelected(false);
                     
        
        if (p.getStatus().equals("Ativo")) {
            rbAtivo.setSelected(true);
            rbInativo.setSelected(false);
        } else if (p.getStatus().equals("Inativo")) {
            rbAtivo.setSelected(false);
            rbInativo.setSelected(true);
        }

        
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(true);
        
    }

    private void excluirCadastro() {

        // Obtém o ID informado no campo txtID e converte para inteiro
        int pos = Integer.parseInt(txtID.getText());

        // Verifica se o ID é válido (maior que 0)
        if (pos > 0) {
            // Exibe uma caixa de diálogo para confirmar a exclusão
            int resposta = JOptionPane.showConfirmDialog(
                    null, // Componente pai (null usa a janela atual)
                    "Deseja realmente excluir o cadastro?", // Mensagem
                    "Confirmação de exclusão", // Título da janela
                    JOptionPane.YES_NO_OPTION // Opções: Sim ou Não
            );

            // Se o usuário clicar em "Sim"
            if (resposta == JOptionPane.YES_OPTION) {
                // Tenta deletar o cadastro com o ID informado
                boolean sucesso = ProdutoDAO.excluir(pos);

                // Mostra mensagem dependendo do sucesso da exclusão
                if (sucesso) {
                    JOptionPane.showMessageDialog(null, "Cadastro excluído com sucesso.");
                    
                    limpar();
                    desabilitarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir o cadastro.");
                }
            }
        } else {
            // Se o ID for inválido, informa o usuário
            JOptionPane.showMessageDialog(null, "ID inválido para exclusão.");
        }
    }
 



}

