package UserInterfaces;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import Classes.Cliente;
import DAO.ClienteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public final class ListClientes extends javax.swing.JFrame {

    private CadastroCliente cadastroFrame;

    public ListClientes() {
        //initComponents();
        // montarETornarTabelaConfigurada(tblClientes);

    }

    public ListClientes(CadastroCliente cadastroFrame) {  //PASSANDO O CADASTRO CLIENTE DIRETAMENTE PARA LISTCLIENTES 
        //Agora, ListClientes tem acesso direto ao objeto correto de CadastroCliente e pode preencher os campos corretamente
        initComponents();
        montarETornarTabelaConfigurada(tblClientes);
        this.cadastroFrame = cadastroFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPesquisar = new javax.swing.JPanel();
        txtPesquisarCliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnSelecionar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");

        pnlPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar cliente por nome"));

        txtPesquisarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPesquisarCliente.setToolTipText("Digite nome do produto para pesquisar");
        txtPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlPesquisarLayout = new javax.swing.GroupLayout(pnlPesquisar);
        pnlPesquisar.setLayout(pnlPesquisarLayout);
        pnlPesquisarLayout.setHorizontalGroup(
            pnlPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPesquisarLayout.setVerticalGroup(
            pnlPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPesquisarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSelecionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check 16px.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.setToolTipText("Adicionar item ");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar 16px.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setToolTipText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionar)
                    .addComponent(btncancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed

        selecionarRegistro();

    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void txtPesquisarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarClienteKeyReleased

        String busca = txtPesquisarCliente.getText().trim(); //Elimina espaços em branco da caixa de texto

        if (busca.isEmpty()) {
            montarETornarTabelaConfigurada(tblClientes);
        } else {
            pesquisarTabelaNome(busca);
        }


    }//GEN-LAST:event_txtPesquisarClienteKeyReleased

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed

        dispose();

    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlPesquisar;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtPesquisarCliente;
    // End of variables declaration//GEN-END:variables

    public void montarETornarTabelaConfigurada(JTable tabelaClientes) {
        String[] colunas = {"ID", "Nome", "CPF"};

        DefaultTableModel modelo = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Impede edição de todas as células
            }
        };

        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {  //metodo para selecionar do duplo clique
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2 && tblClientes.getSelectedRow() != -1) {
                    selecionarRegistro();
                }
            }
        });

        List<Cliente> lista = ClienteDAO.listar();

        for (Cliente m : lista) {
            String[] linha = {
                Integer.toString(m.getId()),
                m.getNome(),
                m.getCpf()
            };
            modelo.addRow(linha);
        }

        tabelaClientes.setModel(modelo);

        // Configura a largura das colunas
        tabelaClientes.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        tabelaClientes.getColumnModel().getColumn(1).setPreferredWidth(200); // Nome
        tabelaClientes.getColumnModel().getColumn(2).setPreferredWidth(200); // CPF

        // Alinhar o cabeçalho à esquerda
        JTableHeader header = tabelaClientes.getTableHeader();
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.LEFT);

    }

    public void pesquisarTabelaNome(String nome) {

        String[] colunas = {"ID", "Nome", "CPF"};

        DefaultTableModel modelo = new DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Impede edição de todas as células
            }
        };

        List<Cliente> lista = ClienteDAO.listar();

        // Filtra os clientes cujo nome contém o texto buscado (ignorando maiúsculas/minúsculas)
        for (Cliente m : lista) {
            if (m.getNome().toLowerCase().contains(nome.toLowerCase())) {
                String[] linha = {
                    Integer.toString(m.getId()),
                    m.getNome(),
                    m.getCpf()
                };
                modelo.addRow(linha);
            }
        }

        tblClientes.setModel(modelo);

        // Configura a largura das colunas
        tblClientes.getColumnModel().getColumn(0).setPreferredWidth(50);  // ID
        tblClientes.getColumnModel().getColumn(1).setPreferredWidth(200); // Nome
        tblClientes.getColumnModel().getColumn(2).setPreferredWidth(200); // CPF

        // Alinhar o cabeçalho à esquerda
        JTableHeader header = tblClientes.getTableHeader();
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) header.getDefaultRenderer();
        renderer.setHorizontalAlignment(SwingConstants.LEFT);
    }

    private void selecionarRegistro() {

        List<Cliente> listaCompletaDeClientes = ClienteDAO.listar(); //carrega a lista completa de clientes
        int linhaSelecionada = tblClientes.getSelectedRow(); //pega a linha selecionada da tabela

        if (linhaSelecionada >= 0) {
            // Corrigido: converte corretamente o valor da tabela para inteiro
            String idStr = tblClientes.getValueAt(linhaSelecionada, 0).toString();
            int idSelecionado = Integer.parseInt(idStr);

            // Procurando o cliente na lista completa com o ID selecionado
            Cliente clienteSelecionado = null;
            for (Cliente cliente : listaCompletaDeClientes) {
                if (cliente.getId() == idSelecionado) {
                    clienteSelecionado = cliente;
                    break;
                }
            }

            // Se o cliente foi encontrado
            if (clienteSelecionado != null) {
                // Preenche os campos no CadastroClienteFram              
                cadastroFrame.preencherCampos(clienteSelecionado);  // usamos o atributo passado
                dispose(); // Fecha o JDialog de seleção
            } else {
                JOptionPane.showMessageDialog(this, "Cliente não encontrado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um cliente na tabela.");
        }
    }

}
